//
// Created by lizhi on 3/24/22.
//

#include <stdio.h>
#include <cuda.h>
#include <malloc.h>
#include <cstdlib>
#include <time.h>
#include <iostream>
#include <sys/types.h>
#include <errno.h>
#include <vector>
#include <fstream>
#include <string>
using namespace std;
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[16];
  __shared__ float pad_temp_shared[1392];
  __shared__ float kernel_shared[144];
  float pad_temp_shared_local[12];
  float kernel_shared_local[12];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(8)] = 0.000000e+00f;
  compute_local[(12)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(9)] = 0.000000e+00f;
  compute_local[(13)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(10)] = 0.000000e+00f;
  compute_local[(14)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  compute_local[(11)] = 0.000000e+00f;
  compute_local[(15)] = 0.000000e+00f;
  for (int rc_outer = 0; rc_outer < 8; ++rc_outer) {
    __syncthreads();
    pad_temp_shared[((((int)threadIdx.x) * 25))] = (((((1 <= ((((int)blockIdx.y) * 4) + (((((int)threadIdx.x) * 25) % 348) / 58))) && (((((int)blockIdx.y) * 4) + (((((int)threadIdx.x) * 25) % 348) / 58)) < 57)) && (1 <= ((((int)threadIdx.x) * 25) % 58))) && (((((int)threadIdx.x) * 25) % 58) < 57)) ? data[(((((((rc_outer * 12544) + (((((int)threadIdx.x) * 25) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + ((((((int)threadIdx.x) * 25) % 348) / 58) * 56)) + ((((int)threadIdx.x) * 25) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 1))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 1) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 1) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 1) % 58))) && ((((((int)threadIdx.x) * 25) + 1) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 1) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 1) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 1) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 2))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 2) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 2) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 2) % 58))) && ((((((int)threadIdx.x) * 25) + 2) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 2) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 2) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 2) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 3))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 3) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 3) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 3) % 58))) && ((((((int)threadIdx.x) * 25) + 3) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 3) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 3) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 3) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 4))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 4) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 4) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 4) % 58))) && ((((((int)threadIdx.x) * 25) + 4) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 4) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 4) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 4) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 5))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 5) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 5) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 5) % 58))) && ((((((int)threadIdx.x) * 25) + 5) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 5) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 5) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 5) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 6))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 6) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 6) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 6) % 58))) && ((((((int)threadIdx.x) * 25) + 6) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 6) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 6) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 6) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 7))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 7) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 7) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 7) % 58))) && ((((((int)threadIdx.x) * 25) + 7) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 7) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 7) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 7) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 8))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 8) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 8) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 8) % 58))) && ((((((int)threadIdx.x) * 25) + 8) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 8) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 8) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 8) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 9))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 9) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 9) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 9) % 58))) && ((((((int)threadIdx.x) * 25) + 9) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 9) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 9) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 9) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 10))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 10) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 10) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 10) % 58))) && ((((((int)threadIdx.x) * 25) + 10) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 10) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 10) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 10) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 11))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 11) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 11) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 11) % 58))) && ((((((int)threadIdx.x) * 25) + 11) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 11) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 11) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 11) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 12))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 12) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 12) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 12) % 58))) && ((((((int)threadIdx.x) * 25) + 12) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 12) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 12) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 12) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 13))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 13) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 13) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 13) % 58))) && ((((((int)threadIdx.x) * 25) + 13) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 13) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 13) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 13) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 14))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 14) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 14) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 14) % 58))) && ((((((int)threadIdx.x) * 25) + 14) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 14) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 14) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 14) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 15))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 15) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 15) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 15) % 58))) && ((((((int)threadIdx.x) * 25) + 15) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 15) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 15) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 15) % 58)) - 57))] : 0.000000e+00f);
    pad_temp_shared[(((((int)threadIdx.x) * 25) + 16))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 16) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 16) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 16) % 58))) && ((((((int)threadIdx.x) * 25) + 16) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 16) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 16) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 16) % 58)) - 57))] : 0.000000e+00f);
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 17))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 17) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 17) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 17) % 58))) && ((((((int)threadIdx.x) * 25) + 17) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 17) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 17) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 17) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 18))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 18) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 18) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 18) % 58))) && ((((((int)threadIdx.x) * 25) + 18) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 18) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 18) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 18) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 19))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 19) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 19) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 19) % 58))) && ((((((int)threadIdx.x) * 25) + 19) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 19) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 19) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 19) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 20))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 20) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 20) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 20) % 58))) && ((((((int)threadIdx.x) * 25) + 20) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 20) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 20) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 20) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 21))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 21) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 21) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 21) % 58))) && ((((((int)threadIdx.x) * 25) + 21) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 21) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 21) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 21) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 22))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 22) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 22) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 22) % 58))) && ((((((int)threadIdx.x) * 25) + 22) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 22) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 22) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 22) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 23))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 23) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 23) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 23) % 58))) && ((((((int)threadIdx.x) * 25) + 23) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 23) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 23) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 23) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 55) {
      pad_temp_shared[(((((int)threadIdx.x) * 25) + 24))] = (((((1 <= ((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 24) % 348) / 58))) && (((((int)blockIdx.y) * 4) + ((((((int)threadIdx.x) * 25) + 24) % 348) / 58)) < 57)) && (1 <= (((((int)threadIdx.x) * 25) + 24) % 58))) && ((((((int)threadIdx.x) * 25) + 24) % 58) < 57)) ? data[(((((((rc_outer * 12544) + ((((((int)threadIdx.x) * 25) + 24) / 348) * 3136)) + (((int)blockIdx.y) * 224)) + (((((((int)threadIdx.x) * 25) + 24) % 348) / 58) * 56)) + (((((int)threadIdx.x) * 25) + 24) % 58)) - 57))] : 0.000000e+00f);
    }
    if (((int)threadIdx.x) < 48) {
      kernel_shared[((((int)threadIdx.x) * 3))] = kernel[(((((((int)blockIdx.z) * 1152) + ((((int)threadIdx.x) / 12) * 288)) + (rc_outer * 36)) + ((((int)threadIdx.x) % 12) * 3)))];
    }
    if (((int)threadIdx.x) < 48) {
      kernel_shared[(((((int)threadIdx.x) * 3) + 1))] = kernel[((((((((int)blockIdx.z) * 1152) + ((((int)threadIdx.x) / 12) * 288)) + (rc_outer * 36)) + ((((int)threadIdx.x) % 12) * 3)) + 1))];
    }
    if (((int)threadIdx.x) < 48) {
      kernel_shared[(((((int)threadIdx.x) * 3) + 2))] = kernel[((((((((int)blockIdx.z) * 1152) + ((((int)threadIdx.x) / 12) * 288)) + (rc_outer * 36)) + ((((int)threadIdx.x) % 12) * 3)) + 2))];
    }
    __syncthreads();
    pad_temp_shared_local[(0)] = pad_temp_shared[(((int)threadIdx.x))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 58))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 116))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 174))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 58))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 116))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 174))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 232))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 116))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 174))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 232))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 290))];
    kernel_shared_local[(0)] = kernel_shared[(0)];
    kernel_shared_local[(1)] = kernel_shared[(3)];
    kernel_shared_local[(2)] = kernel_shared[(6)];
    kernel_shared_local[(3)] = kernel_shared[(36)];
    kernel_shared_local[(4)] = kernel_shared[(39)];
    kernel_shared_local[(5)] = kernel_shared[(42)];
    kernel_shared_local[(6)] = kernel_shared[(72)];
    kernel_shared_local[(7)] = kernel_shared[(75)];
    kernel_shared_local[(8)] = kernel_shared[(78)];
    kernel_shared_local[(9)] = kernel_shared[(108)];
    kernel_shared_local[(10)] = kernel_shared[(111)];
    kernel_shared_local[(11)] = kernel_shared[(114)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 1))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 59))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 117))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 175))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 59))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 117))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 175))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 233))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 117))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 175))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 233))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 291))];
    kernel_shared_local[(0)] = kernel_shared[(1)];
    kernel_shared_local[(1)] = kernel_shared[(4)];
    kernel_shared_local[(2)] = kernel_shared[(7)];
    kernel_shared_local[(3)] = kernel_shared[(37)];
    kernel_shared_local[(4)] = kernel_shared[(40)];
    kernel_shared_local[(5)] = kernel_shared[(43)];
    kernel_shared_local[(6)] = kernel_shared[(73)];
    kernel_shared_local[(7)] = kernel_shared[(76)];
    kernel_shared_local[(8)] = kernel_shared[(79)];
    kernel_shared_local[(9)] = kernel_shared[(109)];
    kernel_shared_local[(10)] = kernel_shared[(112)];
    kernel_shared_local[(11)] = kernel_shared[(115)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 2))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 60))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 118))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 176))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 60))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 118))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 176))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 234))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 118))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 176))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 234))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 292))];
    kernel_shared_local[(0)] = kernel_shared[(2)];
    kernel_shared_local[(1)] = kernel_shared[(5)];
    kernel_shared_local[(2)] = kernel_shared[(8)];
    kernel_shared_local[(3)] = kernel_shared[(38)];
    kernel_shared_local[(4)] = kernel_shared[(41)];
    kernel_shared_local[(5)] = kernel_shared[(44)];
    kernel_shared_local[(6)] = kernel_shared[(74)];
    kernel_shared_local[(7)] = kernel_shared[(77)];
    kernel_shared_local[(8)] = kernel_shared[(80)];
    kernel_shared_local[(9)] = kernel_shared[(110)];
    kernel_shared_local[(10)] = kernel_shared[(113)];
    kernel_shared_local[(11)] = kernel_shared[(116)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 348))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 406))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 464))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 522))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 406))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 464))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 522))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 580))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 464))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 522))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 580))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 638))];
    kernel_shared_local[(0)] = kernel_shared[(9)];
    kernel_shared_local[(1)] = kernel_shared[(12)];
    kernel_shared_local[(2)] = kernel_shared[(15)];
    kernel_shared_local[(3)] = kernel_shared[(45)];
    kernel_shared_local[(4)] = kernel_shared[(48)];
    kernel_shared_local[(5)] = kernel_shared[(51)];
    kernel_shared_local[(6)] = kernel_shared[(81)];
    kernel_shared_local[(7)] = kernel_shared[(84)];
    kernel_shared_local[(8)] = kernel_shared[(87)];
    kernel_shared_local[(9)] = kernel_shared[(117)];
    kernel_shared_local[(10)] = kernel_shared[(120)];
    kernel_shared_local[(11)] = kernel_shared[(123)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 349))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 407))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 465))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 523))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 407))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 465))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 523))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 581))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 465))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 523))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 581))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 639))];
    kernel_shared_local[(0)] = kernel_shared[(10)];
    kernel_shared_local[(1)] = kernel_shared[(13)];
    kernel_shared_local[(2)] = kernel_shared[(16)];
    kernel_shared_local[(3)] = kernel_shared[(46)];
    kernel_shared_local[(4)] = kernel_shared[(49)];
    kernel_shared_local[(5)] = kernel_shared[(52)];
    kernel_shared_local[(6)] = kernel_shared[(82)];
    kernel_shared_local[(7)] = kernel_shared[(85)];
    kernel_shared_local[(8)] = kernel_shared[(88)];
    kernel_shared_local[(9)] = kernel_shared[(118)];
    kernel_shared_local[(10)] = kernel_shared[(121)];
    kernel_shared_local[(11)] = kernel_shared[(124)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 350))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 408))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 466))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 524))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 408))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 466))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 524))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 582))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 466))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 524))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 582))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 640))];
    kernel_shared_local[(0)] = kernel_shared[(11)];
    kernel_shared_local[(1)] = kernel_shared[(14)];
    kernel_shared_local[(2)] = kernel_shared[(17)];
    kernel_shared_local[(3)] = kernel_shared[(47)];
    kernel_shared_local[(4)] = kernel_shared[(50)];
    kernel_shared_local[(5)] = kernel_shared[(53)];
    kernel_shared_local[(6)] = kernel_shared[(83)];
    kernel_shared_local[(7)] = kernel_shared[(86)];
    kernel_shared_local[(8)] = kernel_shared[(89)];
    kernel_shared_local[(9)] = kernel_shared[(119)];
    kernel_shared_local[(10)] = kernel_shared[(122)];
    kernel_shared_local[(11)] = kernel_shared[(125)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 696))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 754))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 812))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 870))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 754))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 812))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 870))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 928))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 812))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 870))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 928))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 986))];
    kernel_shared_local[(0)] = kernel_shared[(18)];
    kernel_shared_local[(1)] = kernel_shared[(21)];
    kernel_shared_local[(2)] = kernel_shared[(24)];
    kernel_shared_local[(3)] = kernel_shared[(54)];
    kernel_shared_local[(4)] = kernel_shared[(57)];
    kernel_shared_local[(5)] = kernel_shared[(60)];
    kernel_shared_local[(6)] = kernel_shared[(90)];
    kernel_shared_local[(7)] = kernel_shared[(93)];
    kernel_shared_local[(8)] = kernel_shared[(96)];
    kernel_shared_local[(9)] = kernel_shared[(126)];
    kernel_shared_local[(10)] = kernel_shared[(129)];
    kernel_shared_local[(11)] = kernel_shared[(132)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 697))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 755))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 813))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 871))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 755))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 813))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 871))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 929))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 813))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 871))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 929))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 987))];
    kernel_shared_local[(0)] = kernel_shared[(19)];
    kernel_shared_local[(1)] = kernel_shared[(22)];
    kernel_shared_local[(2)] = kernel_shared[(25)];
    kernel_shared_local[(3)] = kernel_shared[(55)];
    kernel_shared_local[(4)] = kernel_shared[(58)];
    kernel_shared_local[(5)] = kernel_shared[(61)];
    kernel_shared_local[(6)] = kernel_shared[(91)];
    kernel_shared_local[(7)] = kernel_shared[(94)];
    kernel_shared_local[(8)] = kernel_shared[(97)];
    kernel_shared_local[(9)] = kernel_shared[(127)];
    kernel_shared_local[(10)] = kernel_shared[(130)];
    kernel_shared_local[(11)] = kernel_shared[(133)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 698))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 756))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 814))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 872))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 756))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 814))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 872))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 930))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 814))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 872))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 930))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 988))];
    kernel_shared_local[(0)] = kernel_shared[(20)];
    kernel_shared_local[(1)] = kernel_shared[(23)];
    kernel_shared_local[(2)] = kernel_shared[(26)];
    kernel_shared_local[(3)] = kernel_shared[(56)];
    kernel_shared_local[(4)] = kernel_shared[(59)];
    kernel_shared_local[(5)] = kernel_shared[(62)];
    kernel_shared_local[(6)] = kernel_shared[(92)];
    kernel_shared_local[(7)] = kernel_shared[(95)];
    kernel_shared_local[(8)] = kernel_shared[(98)];
    kernel_shared_local[(9)] = kernel_shared[(128)];
    kernel_shared_local[(10)] = kernel_shared[(131)];
    kernel_shared_local[(11)] = kernel_shared[(134)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 1044))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 1102))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 1160))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 1218))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 1102))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 1160))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 1218))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 1276))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 1160))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 1218))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 1276))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 1334))];
    kernel_shared_local[(0)] = kernel_shared[(27)];
    kernel_shared_local[(1)] = kernel_shared[(30)];
    kernel_shared_local[(2)] = kernel_shared[(33)];
    kernel_shared_local[(3)] = kernel_shared[(63)];
    kernel_shared_local[(4)] = kernel_shared[(66)];
    kernel_shared_local[(5)] = kernel_shared[(69)];
    kernel_shared_local[(6)] = kernel_shared[(99)];
    kernel_shared_local[(7)] = kernel_shared[(102)];
    kernel_shared_local[(8)] = kernel_shared[(105)];
    kernel_shared_local[(9)] = kernel_shared[(135)];
    kernel_shared_local[(10)] = kernel_shared[(138)];
    kernel_shared_local[(11)] = kernel_shared[(141)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 1045))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 1103))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 1161))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 1219))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 1103))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 1161))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 1219))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 1277))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 1161))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 1219))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 1277))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 1335))];
    kernel_shared_local[(0)] = kernel_shared[(28)];
    kernel_shared_local[(1)] = kernel_shared[(31)];
    kernel_shared_local[(2)] = kernel_shared[(34)];
    kernel_shared_local[(3)] = kernel_shared[(64)];
    kernel_shared_local[(4)] = kernel_shared[(67)];
    kernel_shared_local[(5)] = kernel_shared[(70)];
    kernel_shared_local[(6)] = kernel_shared[(100)];
    kernel_shared_local[(7)] = kernel_shared[(103)];
    kernel_shared_local[(8)] = kernel_shared[(106)];
    kernel_shared_local[(9)] = kernel_shared[(136)];
    kernel_shared_local[(10)] = kernel_shared[(139)];
    kernel_shared_local[(11)] = kernel_shared[(142)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.x) + 1046))];
    pad_temp_shared_local[(3)] = pad_temp_shared[((((int)threadIdx.x) + 1104))];
    pad_temp_shared_local[(6)] = pad_temp_shared[((((int)threadIdx.x) + 1162))];
    pad_temp_shared_local[(9)] = pad_temp_shared[((((int)threadIdx.x) + 1220))];
    pad_temp_shared_local[(1)] = pad_temp_shared[((((int)threadIdx.x) + 1104))];
    pad_temp_shared_local[(4)] = pad_temp_shared[((((int)threadIdx.x) + 1162))];
    pad_temp_shared_local[(7)] = pad_temp_shared[((((int)threadIdx.x) + 1220))];
    pad_temp_shared_local[(10)] = pad_temp_shared[((((int)threadIdx.x) + 1278))];
    pad_temp_shared_local[(2)] = pad_temp_shared[((((int)threadIdx.x) + 1162))];
    pad_temp_shared_local[(5)] = pad_temp_shared[((((int)threadIdx.x) + 1220))];
    pad_temp_shared_local[(8)] = pad_temp_shared[((((int)threadIdx.x) + 1278))];
    pad_temp_shared_local[(11)] = pad_temp_shared[((((int)threadIdx.x) + 1336))];
    kernel_shared_local[(0)] = kernel_shared[(29)];
    kernel_shared_local[(1)] = kernel_shared[(32)];
    kernel_shared_local[(2)] = kernel_shared[(35)];
    kernel_shared_local[(3)] = kernel_shared[(65)];
    kernel_shared_local[(4)] = kernel_shared[(68)];
    kernel_shared_local[(5)] = kernel_shared[(71)];
    kernel_shared_local[(6)] = kernel_shared[(101)];
    kernel_shared_local[(7)] = kernel_shared[(104)];
    kernel_shared_local[(8)] = kernel_shared[(107)];
    kernel_shared_local[(9)] = kernel_shared[(137)];
    kernel_shared_local[(10)] = kernel_shared[(140)];
    kernel_shared_local[(11)] = kernel_shared[(143)];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(3)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(3)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(3)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(6)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(6)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(6)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(6)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(9)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(9)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(9)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(9)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(1)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(1)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(1)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(1)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(4)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(4)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(4)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(4)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(7)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(7)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(7)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(7)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(10)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(10)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(10)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(10)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(2)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(2)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(2)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(5)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(5)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(5)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(8)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(8)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(8)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(8)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(11)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(11)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(11)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(11)]));
  }
  compute[((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)))] = compute_local[(0)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 56))] = compute_local[(4)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 112))] = compute_local[(8)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 168))] = compute_local[(12)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 3136))] = compute_local[(1)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 3192))] = compute_local[(5)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 3248))] = compute_local[(9)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 3304))] = compute_local[(13)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 6272))] = compute_local[(2)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 6328))] = compute_local[(6)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 6384))] = compute_local[(10)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 6440))] = compute_local[(14)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 9408))] = compute_local[(3)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 9464))] = compute_local[(7)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 9520))] = compute_local[(11)];
  compute[(((((((int)blockIdx.z) * 12544) + (((int)blockIdx.y) * 224)) + ((int)threadIdx.x)) + 9576))] = compute_local[(15)];
}

int main(int argc, char *argv[]){
    dim3 grid(1,14,8);
    dim3 block(56,1,1);

    int C = atoi(argv[1]);
    int H = atoi(argv[3]);
    int W = atoi(argv[4]);
    int N = atoi(argv[2]);
    int data_size = C*H*W;

    float *input;
    cudaMalloc(&input,data_size*sizeof(float));
    float *weight;
    cudaMalloc(&weight,N*C*9*sizeof(float));
    float *output;
    cudaMalloc(&output,N*H*W*sizeof(float));

    cudaDeviceSynchronize();
    float inference_time = 0.0f;
    cudaEvent_t event_start;
    cudaEvent_t event_stop;
    cudaEventCreate(&event_start);
    cudaEventCreate(&event_stop);
    for(int i=0;i<1024;++i){
        cudaEventRecord(event_start);
        default_function_kernel0<<<grid,block>>>(input,weight,output);
        cudaEventRecord(event_stop);
        cudaEventSynchronize(event_stop);
        float temp_time;
        cudaEventElapsedTime(&temp_time, event_start, event_stop);
        inference_time += temp_time;
    }
    cout<<C<<","<<N<<","<<H<<","<<W<<","<<inference_time/1024<<endl;
    return 0;
}
