//

#include <stdio.h>
#include <cuda.h>
#include <malloc.h>
#include <cstdlib>
#include <time.h>
#include <iostream>
#include <sys/types.h>
#include <errno.h>
#include <vector>
#include <fstream>
#include <string>
using namespace std;
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[4];
  __shared__ float pad_temp_shared[288];
  __shared__ float kernel_shared[864];
  float pad_temp_shared_local[6];
  float kernel_shared_local[6];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  for (int rc_outer = 0; rc_outer < 16; ++rc_outer) {
    __syncthreads();
    pad_temp_shared[(((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)))] = (((((1 <= ((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) % 9))) && (((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) % 9)) < 15)) && (1 <= ((((int)blockIdx.x) * 2) + ((((int)threadIdx.y) * 7) & 3)))) && (((((int)blockIdx.x) * 2) + ((((int)threadIdx.y) * 7) & 3)) < 15)) ? data[((((((((rc_outer * 1568) + ((((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) / 9) * 196)) + (((int)blockIdx.y) * 98)) + ((((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) % 9) * 14)) + (((int)blockIdx.x) * 2)) + ((((int)threadIdx.y) * 7) & 3)) - 15))] : 0.000000e+00f);
    pad_temp_shared[((((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) + 1))] = (((((1 <= ((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 1) >> 2)) % 9))) && (((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 1) >> 2)) % 9)) < 15)) && (1 <= ((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 1) & 3)))) && (((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 1) & 3)) < 15)) ? data[((((((((rc_outer * 1568) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 1) >> 2)) / 9) * 196)) + (((int)blockIdx.y) * 98)) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 1) >> 2)) % 9) * 14)) + (((int)blockIdx.x) * 2)) + (((((int)threadIdx.y) * 7) + 1) & 3)) - 15))] : 0.000000e+00f);
    pad_temp_shared[((((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) + 2))] = (((((1 <= ((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 2) >> 2)) % 9))) && (((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 2) >> 2)) % 9)) < 15)) && (1 <= ((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 2) & 3)))) && (((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 2) & 3)) < 15)) ? data[((((((((rc_outer * 1568) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 2) >> 2)) / 9) * 196)) + (((int)blockIdx.y) * 98)) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 2) >> 2)) % 9) * 14)) + (((int)blockIdx.x) * 2)) + (((((int)threadIdx.y) * 7) + 2) & 3)) - 15))] : 0.000000e+00f);
    pad_temp_shared[((((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) + 3))] = (((((1 <= ((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 3) >> 2)) % 9))) && (((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 3) >> 2)) % 9)) < 15)) && (1 <= ((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 3) & 3)))) && (((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 3) & 3)) < 15)) ? data[((((((((rc_outer * 1568) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 3) >> 2)) / 9) * 196)) + (((int)blockIdx.y) * 98)) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 3) >> 2)) % 9) * 14)) + (((int)blockIdx.x) * 2)) + (((((int)threadIdx.y) * 7) + 3) & 3)) - 15))] : 0.000000e+00f);
    pad_temp_shared[((((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) + 4))] = (((((1 <= ((((int)blockIdx.y) * 7) + ((((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) + 1) % 9))) && (((((int)blockIdx.y) * 7) + ((((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) + 1) % 9)) < 15)) && (1 <= ((((int)blockIdx.x) * 2) + ((((int)threadIdx.y) * 7) & 3)))) && (((((int)blockIdx.x) * 2) + ((((int)threadIdx.y) * 7) & 3)) < 15)) ? data[((((((((rc_outer * 1568) + (((((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) + 1) / 9) * 196)) + (((int)blockIdx.y) * 98)) + (((((((int)threadIdx.z) * 12) + ((((int)threadIdx.y) * 7) >> 2)) + 1) % 9) * 14)) + (((int)blockIdx.x) * 2)) + ((((int)threadIdx.y) * 7) & 3)) - 15))] : 0.000000e+00f);
    pad_temp_shared[((((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) + 5))] = (((((1 <= ((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 5) >> 2)) % 9))) && (((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 5) >> 2)) % 9)) < 15)) && (1 <= ((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 1) & 3)))) && (((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 1) & 3)) < 15)) ? data[((((((((rc_outer * 1568) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 5) >> 2)) / 9) * 196)) + (((int)blockIdx.y) * 98)) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 5) >> 2)) % 9) * 14)) + (((int)blockIdx.x) * 2)) + (((((int)threadIdx.y) * 7) + 1) & 3)) - 15))] : 0.000000e+00f);
    if (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 6) >> 2)) < 72) {
      if (((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) < 282) {
        if (((int)threadIdx.y) < 6) {
          pad_temp_shared[((((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) + 6))] = (((((1 <= ((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 6) >> 2)) % 9))) && (((((int)blockIdx.y) * 7) + (((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 6) >> 2)) % 9)) < 15)) && (1 <= ((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 2) & 3)))) && (((((int)blockIdx.x) * 2) + (((((int)threadIdx.y) * 7) + 2) & 3)) < 15)) ? data[((((((((rc_outer * 1568) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 6) >> 2)) / 9) * 196)) + (((int)blockIdx.y) * 98)) + ((((((int)threadIdx.z) * 12) + (((((int)threadIdx.y) * 7) + 6) >> 2)) % 9) * 14)) + (((int)blockIdx.x) * 2)) + (((((int)threadIdx.y) * 7) + 2) & 3)) - 15))] : 0.000000e+00f);
        }
      }
    }
    kernel_shared[(((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)))] = kernel[((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + (((((int)threadIdx.y) * 7) / 24) * 1152)) + (rc_outer * 72)) + (((((int)threadIdx.y) * 7) % 24) * 3)))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 1))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + (((((int)threadIdx.y) * 7) / 24) * 1152)) + (rc_outer * 72)) + (((((int)threadIdx.y) * 7) % 24) * 3)) + 1))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 2))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + (((((int)threadIdx.y) * 7) / 24) * 1152)) + (rc_outer * 72)) + (((((int)threadIdx.y) * 7) % 24) * 3)) + 2))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 3))] = kernel[((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 1) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 1) % 24) * 3)))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 4))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 1) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 1) % 24) * 3)) + 1))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 5))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 1) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 1) % 24) * 3)) + 2))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 6))] = kernel[((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 2) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 2) % 24) * 3)))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 7))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 2) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 2) % 24) * 3)) + 1))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 8))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 2) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 2) % 24) * 3)) + 2))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 9))] = kernel[((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 3) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 3) % 24) * 3)))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 10))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 3) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 3) % 24) * 3)) + 1))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 11))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 3) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 3) % 24) * 3)) + 2))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 12))] = kernel[((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 4) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 4) % 24) * 3)))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 13))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 4) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 4) % 24) * 3)) + 1))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 14))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 4) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 4) % 24) * 3)) + 2))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 15))] = kernel[((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 5) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 5) % 24) * 3)))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 16))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 5) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 5) % 24) * 3)) + 1))];
    kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 17))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 5) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 5) % 24) * 3)) + 2))];
    if (((((int)threadIdx.z) * 2) + (((((int)threadIdx.y) * 7) + 6) / 24)) < 12) {
      if (((((int)threadIdx.z) * 16) + ((((int)threadIdx.y) * 7) / 3)) < 94) {
        if (((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) < 282) {
          if (((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) < 846) {
            if (((int)threadIdx.y) < 6) {
              kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 18))] = kernel[((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 6) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 6) % 24) * 3)))];
            }
          }
        }
      }
    }
    if (((((int)threadIdx.z) * 2) + (((((int)threadIdx.y) * 7) + 6) / 24)) < 12) {
      if (((((int)threadIdx.z) * 16) + ((((int)threadIdx.y) * 7) / 3)) < 94) {
        if (((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) < 282) {
          if (((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) < 845) {
            if (((int)threadIdx.y) < 6) {
              kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 19))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 6) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 6) % 24) * 3)) + 1))];
            }
          }
        }
      }
    }
    if (((((int)threadIdx.z) * 2) + (((((int)threadIdx.y) * 7) + 6) / 24)) < 12) {
      if (((((int)threadIdx.z) * 16) + ((((int)threadIdx.y) * 7) / 3)) < 94) {
        if (((((int)threadIdx.z) * 48) + (((int)threadIdx.y) * 7)) < 282) {
          if (((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) < 844) {
            if (((int)threadIdx.y) < 6) {
              kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.y) * 21)) + 20))] = kernel[(((((((((int)blockIdx.z) * 13824) + (((int)threadIdx.z) * 2304)) + ((((((int)threadIdx.y) * 7) + 6) / 24) * 1152)) + (rc_outer * 72)) + ((((((int)threadIdx.y) * 7) + 6) % 24) * 3)) + 2))];
            }
          }
        }
      }
    }
    __syncthreads();
    pad_temp_shared_local[(0)] = pad_temp_shared[((((int)threadIdx.y) * 4))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 1))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 4))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 5))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 8))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 9))];
    kernel_shared_local[(0)] = kernel_shared[((((int)threadIdx.z) * 72))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 432))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 3))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 435))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 6))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 438))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 1))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 2))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 5))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 6))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 9))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 10))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 1))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 433))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 4))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 436))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 7))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 439))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 2))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 3))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 6))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 7))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 10))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 11))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 2))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 434))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 5))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 437))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 8))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 440))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 36))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 37))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 40))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 41))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 44))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 45))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 9))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 441))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 12))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 444))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 15))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 447))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 37))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 38))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 41))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 42))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 45))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 46))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 10))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 442))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 13))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 445))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 16))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 448))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 38))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 39))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 42))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 43))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 46))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 47))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 11))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 443))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 14))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 446))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 17))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 449))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 72))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 73))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 76))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 77))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 80))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 81))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 18))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 450))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 21))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 453))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 24))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 456))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 73))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 74))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 77))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 78))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 81))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 82))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 19))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 451))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 22))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 454))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 25))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 457))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 74))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 75))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 78))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 79))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 82))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 83))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 20))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 452))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 23))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 455))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 26))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 458))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 108))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 109))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 112))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 113))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 116))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 117))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 27))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 459))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 30))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 462))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 33))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 465))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 109))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 110))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 113))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 114))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 117))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 118))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 28))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 460))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 31))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 463))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 34))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 466))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 110))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 111))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 114))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 115))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 118))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 119))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 29))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 461))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 32))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 464))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 35))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 467))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 144))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 145))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 148))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 149))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 152))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 153))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 36))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 468))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 39))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 471))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 42))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 474))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 145))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 146))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 149))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 150))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 153))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 154))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 37))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 469))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 40))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 472))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 43))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 475))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 146))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 147))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 150))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 151))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 154))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 155))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 38))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 470))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 41))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 473))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 44))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 476))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 180))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 181))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 184))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 185))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 188))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 189))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 45))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 477))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 48))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 480))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 51))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 483))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 181))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 182))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 185))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 186))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 189))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 190))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 46))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 478))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 49))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 481))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 52))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 484))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 182))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 183))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 186))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 187))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 190))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 191))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 47))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 479))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 50))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 482))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 53))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 485))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 216))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 217))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 220))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 221))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 224))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 225))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 54))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 486))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 57))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 489))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 60))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 492))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 217))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 218))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 221))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 222))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 225))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 226))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 55))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 487))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 58))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 490))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 61))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 493))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 218))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 219))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 222))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 223))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 226))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 227))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 56))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 488))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 59))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 491))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 62))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 494))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 252))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 253))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 256))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 257))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 260))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 261))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 63))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 495))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 66))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 498))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 69))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 501))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 253))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 254))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 257))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 258))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 261))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 262))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 64))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 496))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 67))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 499))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 70))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 502))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
    pad_temp_shared_local[(0)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 254))];
    pad_temp_shared_local[(1)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 255))];
    pad_temp_shared_local[(2)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 258))];
    pad_temp_shared_local[(3)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 259))];
    pad_temp_shared_local[(4)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 262))];
    pad_temp_shared_local[(5)] = pad_temp_shared[(((((int)threadIdx.y) * 4) + 263))];
    kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 72) + 65))];
    kernel_shared_local[(3)] = kernel_shared[(((((int)threadIdx.z) * 72) + 497))];
    kernel_shared_local[(1)] = kernel_shared[(((((int)threadIdx.z) * 72) + 68))];
    kernel_shared_local[(4)] = kernel_shared[(((((int)threadIdx.z) * 72) + 500))];
    kernel_shared_local[(2)] = kernel_shared[(((((int)threadIdx.z) * 72) + 71))];
    kernel_shared_local[(5)] = kernel_shared[(((((int)threadIdx.z) * 72) + 503))];
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(3)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(3)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(1)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(4)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(4)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(2)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(5)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(5)]));
  }
  compute[((((((((int)blockIdx.z) * 2352) + (((int)threadIdx.z) * 196)) + (((int)blockIdx.y) * 98)) + (((int)threadIdx.y) * 14)) + (((int)blockIdx.x) * 2)))] = compute_local[(0)];
  compute[(((((((((int)blockIdx.z) * 2352) + (((int)threadIdx.z) * 196)) + (((int)blockIdx.y) * 98)) + (((int)threadIdx.y) * 14)) + (((int)blockIdx.x) * 2)) + 1176))] = compute_local[(2)];
  compute[(((((((((int)blockIdx.z) * 2352) + (((int)threadIdx.z) * 196)) + (((int)blockIdx.y) * 98)) + (((int)threadIdx.y) * 14)) + (((int)blockIdx.x) * 2)) + 1))] = compute_local[(1)];
  compute[(((((((((int)blockIdx.z) * 2352) + (((int)threadIdx.z) * 196)) + (((int)blockIdx.y) * 98)) + (((int)threadIdx.y) * 14)) + (((int)blockIdx.x) * 2)) + 1177))] = compute_local[(3)];
}

//grid=(7,1,6),  block=(1,2,8)
int main(int argc, char *argv[]){
    dim3 grid(7,2,8);
    dim3 block(1,7,6);
    int C = atoi(argv[1]);
    int H = atoi(argv[3]);
    int W = atoi(argv[4]);
    int N = atoi(argv[2]);
    int data_size = C*H*W;

    float *input;
    cudaMalloc(&input,data_size*sizeof(float));
    float *weight;
    cudaMalloc(&weight,N*C*9*sizeof(float));
    float *output;
    cudaMalloc(&output,N*H*W*sizeof(float));

    cudaDeviceSynchronize();
    float inference_time = 0.0f;
    cudaEvent_t event_start;
    cudaEvent_t event_stop;
    cudaEventCreate(&event_start);
    cudaEventCreate(&event_stop);
    for(int i=0;i<1024;++i){
        cudaEventRecord(event_start);
        default_function_kernel0<<<grid,block>>>(input,weight,output);
        cudaEventRecord(event_stop);
        cudaEventSynchronize(event_stop);
        float temp_time;
        cudaEventElapsedTime(&temp_time, event_start, event_stop);
        inference_time += temp_time;
    }
    cout<<C<<","<<N<<","<<H<<","<<W<<","<<inference_time/1024<<endl;
    return 0;
}
