//
// Created by lizhi on 3/24/22.
//

#include <stdio.h>
#include <cuda.h>
#include <malloc.h>
#include <cstdlib>
#include <time.h>
#include <iostream>
#include <sys/types.h>
#include <errno.h>
#include <vector>
#include <fstream>
#include <string>
using namespace std;
extern "C" __global__ void default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ compute) {
  float compute_local[14];
  __shared__ float pad_temp_shared[2880];
  __shared__ float kernel_shared[3456];
  float pad_temp_shared_local[56];
  float kernel_shared_local[4];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  compute_local[(8)] = 0.000000e+00f;
  compute_local[(9)] = 0.000000e+00f;
  compute_local[(10)] = 0.000000e+00f;
  compute_local[(11)] = 0.000000e+00f;
  compute_local[(12)] = 0.000000e+00f;
  compute_local[(13)] = 0.000000e+00f;
  for (int rc_outer = 0; rc_outer < 4; ++rc_outer) {
    for (int ry_outer = 0; ry_outer < 3; ++ry_outer) {
      __syncthreads();
      pad_temp_shared[(((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)))] = 0.000000e+00f;
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 1))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 28))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 2))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 27))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 3))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 26))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 4))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 25))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 5))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 24))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 6))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 23))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 7))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 22))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 8))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 21))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 9))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 20))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 10))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 19))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 11))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 18))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 12))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 17))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 13))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 16))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 14))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 15))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 15))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 14))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 16))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 13))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 17))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 12))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 18))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 11))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 19))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 10))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 20))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 9))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 21))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 8))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 22))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 7))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 23))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 6))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 24))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 5))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 25))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 4))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 26))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 3))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 27))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 2))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 28))] = (((1 <= (((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1))) && ((((((int)blockIdx.y) * 2) + ry_outer) + (((int)threadIdx.x) & 1)) < 29)) ? data[((((((((rc_outer * 37632) + (((int)threadIdx.z) * 1568)) + ((((int)threadIdx.x) >> 1) * 784)) + (((int)blockIdx.y) * 56)) + (ry_outer * 28)) + ((((int)threadIdx.x) & 1) * 28)) - 1))] : 0.000000e+00f);
      pad_temp_shared[((((((int)threadIdx.z) * 120) + (((int)threadIdx.x) * 30)) + 29))] = 0.000000e+00f;
      kernel_shared[(((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)))] = kernel[((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 1))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 1))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 2))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 2))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 3))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 9))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 4))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 10))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 5))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 11))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 6))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 18))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 7))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 19))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 8))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 20))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 9))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 27))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 10))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 28))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 11))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 29))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 12))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 36))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 13))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 37))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 14))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 38))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 15))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 45))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 16))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 46))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 17))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 47))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 18))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 54))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 19))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 55))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 20))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 56))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 21))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 63))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 22))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 64))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 23))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 65))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 24))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 72))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 25))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 73))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 26))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 74))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 27))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 81))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 28))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 82))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 29))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 83))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 30))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 90))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 31))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 91))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 32))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 92))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 33))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 99))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 34))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 100))];
      kernel_shared[((((((int)threadIdx.z) * 144) + (((int)threadIdx.x) * 36)) + 35))] = kernel[(((((((((int)blockIdx.z) * 41472) + (((int)threadIdx.z) * 1728)) + (rc_outer * 432)) + (((int)threadIdx.x) * 108)) + (ry_outer * 3)) + 101))];
      __syncthreads();
      for (int rc_inner_outer = 0; rc_inner_outer < 12; ++rc_inner_outer) {
        pad_temp_shared_local[(0)] = pad_temp_shared[(((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)))];
        pad_temp_shared_local[(1)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 1))];
        pad_temp_shared_local[(2)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 2))];
        pad_temp_shared_local[(3)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 3))];
        pad_temp_shared_local[(4)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 4))];
        pad_temp_shared_local[(5)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 5))];
        pad_temp_shared_local[(6)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 6))];
        pad_temp_shared_local[(7)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 30))];
        pad_temp_shared_local[(8)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 31))];
        pad_temp_shared_local[(9)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 32))];
        pad_temp_shared_local[(10)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 33))];
        pad_temp_shared_local[(11)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 34))];
        pad_temp_shared_local[(12)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 35))];
        pad_temp_shared_local[(13)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 36))];
        pad_temp_shared_local[(14)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 60))];
        pad_temp_shared_local[(15)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 61))];
        pad_temp_shared_local[(16)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 62))];
        pad_temp_shared_local[(17)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 63))];
        pad_temp_shared_local[(18)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 64))];
        pad_temp_shared_local[(19)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 65))];
        pad_temp_shared_local[(20)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 66))];
        pad_temp_shared_local[(21)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 90))];
        pad_temp_shared_local[(22)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 91))];
        pad_temp_shared_local[(23)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 92))];
        pad_temp_shared_local[(24)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 93))];
        pad_temp_shared_local[(25)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 94))];
        pad_temp_shared_local[(26)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 95))];
        pad_temp_shared_local[(27)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 96))];
        pad_temp_shared_local[(28)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 120))];
        pad_temp_shared_local[(29)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 121))];
        pad_temp_shared_local[(30)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 122))];
        pad_temp_shared_local[(31)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 123))];
        pad_temp_shared_local[(32)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 124))];
        pad_temp_shared_local[(33)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 125))];
        pad_temp_shared_local[(34)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 126))];
        pad_temp_shared_local[(35)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 150))];
        pad_temp_shared_local[(36)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 151))];
        pad_temp_shared_local[(37)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 152))];
        pad_temp_shared_local[(38)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 153))];
        pad_temp_shared_local[(39)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 154))];
        pad_temp_shared_local[(40)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 155))];
        pad_temp_shared_local[(41)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 156))];
        pad_temp_shared_local[(42)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 180))];
        pad_temp_shared_local[(43)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 181))];
        pad_temp_shared_local[(44)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 182))];
        pad_temp_shared_local[(45)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 183))];
        pad_temp_shared_local[(46)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 184))];
        pad_temp_shared_local[(47)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 185))];
        pad_temp_shared_local[(48)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 186))];
        pad_temp_shared_local[(49)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 210))];
        pad_temp_shared_local[(50)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 211))];
        pad_temp_shared_local[(51)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 212))];
        pad_temp_shared_local[(52)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 213))];
        pad_temp_shared_local[(53)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 214))];
        pad_temp_shared_local[(54)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 215))];
        pad_temp_shared_local[(55)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 216))];
        kernel_shared_local[(0)] = kernel_shared[(((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)))];
        kernel_shared_local[(1)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 3))];
        kernel_shared_local[(2)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 6))];
        kernel_shared_local[(3)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 9))];
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(0)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(0)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(0)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(0)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(0)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(0)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(0)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(12)] * kernel_shared_local[(0)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(13)] * kernel_shared_local[(0)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(14)] * kernel_shared_local[(1)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(15)] * kernel_shared_local[(1)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(16)] * kernel_shared_local[(1)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(17)] * kernel_shared_local[(1)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(18)] * kernel_shared_local[(1)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(19)] * kernel_shared_local[(1)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(20)] * kernel_shared_local[(1)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(21)] * kernel_shared_local[(1)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(22)] * kernel_shared_local[(1)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(23)] * kernel_shared_local[(1)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(24)] * kernel_shared_local[(1)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(25)] * kernel_shared_local[(1)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(26)] * kernel_shared_local[(1)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(27)] * kernel_shared_local[(1)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(28)] * kernel_shared_local[(2)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(29)] * kernel_shared_local[(2)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(30)] * kernel_shared_local[(2)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(31)] * kernel_shared_local[(2)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(32)] * kernel_shared_local[(2)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(33)] * kernel_shared_local[(2)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(34)] * kernel_shared_local[(2)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(35)] * kernel_shared_local[(2)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(36)] * kernel_shared_local[(2)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(37)] * kernel_shared_local[(2)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(38)] * kernel_shared_local[(2)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(39)] * kernel_shared_local[(2)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(40)] * kernel_shared_local[(2)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(41)] * kernel_shared_local[(2)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(42)] * kernel_shared_local[(3)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(43)] * kernel_shared_local[(3)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(44)] * kernel_shared_local[(3)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(45)] * kernel_shared_local[(3)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(46)] * kernel_shared_local[(3)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(47)] * kernel_shared_local[(3)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(48)] * kernel_shared_local[(3)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(49)] * kernel_shared_local[(3)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(50)] * kernel_shared_local[(3)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(51)] * kernel_shared_local[(3)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(52)] * kernel_shared_local[(3)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(53)] * kernel_shared_local[(3)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(54)] * kernel_shared_local[(3)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(55)] * kernel_shared_local[(3)]));
        pad_temp_shared_local[(0)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 1))];
        pad_temp_shared_local[(1)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 2))];
        pad_temp_shared_local[(2)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 3))];
        pad_temp_shared_local[(3)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 4))];
        pad_temp_shared_local[(4)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 5))];
        pad_temp_shared_local[(5)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 6))];
        pad_temp_shared_local[(6)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 7))];
        pad_temp_shared_local[(7)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 31))];
        pad_temp_shared_local[(8)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 32))];
        pad_temp_shared_local[(9)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 33))];
        pad_temp_shared_local[(10)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 34))];
        pad_temp_shared_local[(11)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 35))];
        pad_temp_shared_local[(12)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 36))];
        pad_temp_shared_local[(13)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 37))];
        pad_temp_shared_local[(14)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 61))];
        pad_temp_shared_local[(15)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 62))];
        pad_temp_shared_local[(16)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 63))];
        pad_temp_shared_local[(17)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 64))];
        pad_temp_shared_local[(18)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 65))];
        pad_temp_shared_local[(19)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 66))];
        pad_temp_shared_local[(20)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 67))];
        pad_temp_shared_local[(21)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 91))];
        pad_temp_shared_local[(22)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 92))];
        pad_temp_shared_local[(23)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 93))];
        pad_temp_shared_local[(24)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 94))];
        pad_temp_shared_local[(25)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 95))];
        pad_temp_shared_local[(26)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 96))];
        pad_temp_shared_local[(27)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 97))];
        pad_temp_shared_local[(28)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 121))];
        pad_temp_shared_local[(29)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 122))];
        pad_temp_shared_local[(30)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 123))];
        pad_temp_shared_local[(31)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 124))];
        pad_temp_shared_local[(32)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 125))];
        pad_temp_shared_local[(33)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 126))];
        pad_temp_shared_local[(34)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 127))];
        pad_temp_shared_local[(35)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 151))];
        pad_temp_shared_local[(36)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 152))];
        pad_temp_shared_local[(37)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 153))];
        pad_temp_shared_local[(38)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 154))];
        pad_temp_shared_local[(39)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 155))];
        pad_temp_shared_local[(40)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 156))];
        pad_temp_shared_local[(41)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 157))];
        pad_temp_shared_local[(42)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 181))];
        pad_temp_shared_local[(43)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 182))];
        pad_temp_shared_local[(44)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 183))];
        pad_temp_shared_local[(45)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 184))];
        pad_temp_shared_local[(46)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 185))];
        pad_temp_shared_local[(47)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 186))];
        pad_temp_shared_local[(48)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 187))];
        pad_temp_shared_local[(49)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 211))];
        pad_temp_shared_local[(50)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 212))];
        pad_temp_shared_local[(51)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 213))];
        pad_temp_shared_local[(52)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 214))];
        pad_temp_shared_local[(53)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 215))];
        pad_temp_shared_local[(54)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 216))];
        pad_temp_shared_local[(55)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 217))];
        kernel_shared_local[(0)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 1))];
        kernel_shared_local[(1)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 4))];
        kernel_shared_local[(2)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 7))];
        kernel_shared_local[(3)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 10))];
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(0)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(0)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(0)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(0)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(0)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(0)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(0)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(12)] * kernel_shared_local[(0)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(13)] * kernel_shared_local[(0)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(14)] * kernel_shared_local[(1)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(15)] * kernel_shared_local[(1)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(16)] * kernel_shared_local[(1)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(17)] * kernel_shared_local[(1)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(18)] * kernel_shared_local[(1)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(19)] * kernel_shared_local[(1)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(20)] * kernel_shared_local[(1)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(21)] * kernel_shared_local[(1)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(22)] * kernel_shared_local[(1)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(23)] * kernel_shared_local[(1)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(24)] * kernel_shared_local[(1)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(25)] * kernel_shared_local[(1)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(26)] * kernel_shared_local[(1)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(27)] * kernel_shared_local[(1)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(28)] * kernel_shared_local[(2)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(29)] * kernel_shared_local[(2)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(30)] * kernel_shared_local[(2)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(31)] * kernel_shared_local[(2)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(32)] * kernel_shared_local[(2)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(33)] * kernel_shared_local[(2)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(34)] * kernel_shared_local[(2)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(35)] * kernel_shared_local[(2)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(36)] * kernel_shared_local[(2)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(37)] * kernel_shared_local[(2)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(38)] * kernel_shared_local[(2)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(39)] * kernel_shared_local[(2)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(40)] * kernel_shared_local[(2)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(41)] * kernel_shared_local[(2)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(42)] * kernel_shared_local[(3)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(43)] * kernel_shared_local[(3)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(44)] * kernel_shared_local[(3)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(45)] * kernel_shared_local[(3)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(46)] * kernel_shared_local[(3)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(47)] * kernel_shared_local[(3)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(48)] * kernel_shared_local[(3)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(49)] * kernel_shared_local[(3)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(50)] * kernel_shared_local[(3)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(51)] * kernel_shared_local[(3)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(52)] * kernel_shared_local[(3)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(53)] * kernel_shared_local[(3)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(54)] * kernel_shared_local[(3)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(55)] * kernel_shared_local[(3)]));
        pad_temp_shared_local[(0)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 2))];
        pad_temp_shared_local[(1)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 3))];
        pad_temp_shared_local[(2)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 4))];
        pad_temp_shared_local[(3)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 5))];
        pad_temp_shared_local[(4)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 6))];
        pad_temp_shared_local[(5)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 7))];
        pad_temp_shared_local[(6)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 8))];
        pad_temp_shared_local[(7)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 32))];
        pad_temp_shared_local[(8)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 33))];
        pad_temp_shared_local[(9)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 34))];
        pad_temp_shared_local[(10)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 35))];
        pad_temp_shared_local[(11)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 36))];
        pad_temp_shared_local[(12)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 37))];
        pad_temp_shared_local[(13)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 38))];
        pad_temp_shared_local[(14)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 62))];
        pad_temp_shared_local[(15)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 63))];
        pad_temp_shared_local[(16)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 64))];
        pad_temp_shared_local[(17)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 65))];
        pad_temp_shared_local[(18)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 66))];
        pad_temp_shared_local[(19)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 67))];
        pad_temp_shared_local[(20)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 68))];
        pad_temp_shared_local[(21)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 92))];
        pad_temp_shared_local[(22)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 93))];
        pad_temp_shared_local[(23)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 94))];
        pad_temp_shared_local[(24)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 95))];
        pad_temp_shared_local[(25)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 96))];
        pad_temp_shared_local[(26)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 97))];
        pad_temp_shared_local[(27)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 98))];
        pad_temp_shared_local[(28)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 122))];
        pad_temp_shared_local[(29)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 123))];
        pad_temp_shared_local[(30)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 124))];
        pad_temp_shared_local[(31)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 125))];
        pad_temp_shared_local[(32)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 126))];
        pad_temp_shared_local[(33)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 127))];
        pad_temp_shared_local[(34)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 128))];
        pad_temp_shared_local[(35)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 152))];
        pad_temp_shared_local[(36)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 153))];
        pad_temp_shared_local[(37)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 154))];
        pad_temp_shared_local[(38)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 155))];
        pad_temp_shared_local[(39)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 156))];
        pad_temp_shared_local[(40)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 157))];
        pad_temp_shared_local[(41)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 158))];
        pad_temp_shared_local[(42)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 182))];
        pad_temp_shared_local[(43)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 183))];
        pad_temp_shared_local[(44)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 184))];
        pad_temp_shared_local[(45)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 185))];
        pad_temp_shared_local[(46)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 186))];
        pad_temp_shared_local[(47)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 187))];
        pad_temp_shared_local[(48)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 188))];
        pad_temp_shared_local[(49)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 212))];
        pad_temp_shared_local[(50)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 213))];
        pad_temp_shared_local[(51)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 214))];
        pad_temp_shared_local[(52)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 215))];
        pad_temp_shared_local[(53)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 216))];
        pad_temp_shared_local[(54)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 217))];
        pad_temp_shared_local[(55)] = pad_temp_shared[((((rc_inner_outer * 240) + (((int)threadIdx.x) * 7)) + 218))];
        kernel_shared_local[(0)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 2))];
        kernel_shared_local[(1)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 5))];
        kernel_shared_local[(2)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 8))];
        kernel_shared_local[(3)] = kernel_shared[((((((int)threadIdx.z) * 144) + (rc_inner_outer * 12)) + 11))];
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(0)] * kernel_shared_local[(0)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(1)] * kernel_shared_local[(0)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(2)] * kernel_shared_local[(0)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(3)] * kernel_shared_local[(0)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(4)] * kernel_shared_local[(0)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(5)] * kernel_shared_local[(0)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(6)] * kernel_shared_local[(0)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(7)] * kernel_shared_local[(0)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(8)] * kernel_shared_local[(0)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(9)] * kernel_shared_local[(0)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(10)] * kernel_shared_local[(0)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(11)] * kernel_shared_local[(0)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(12)] * kernel_shared_local[(0)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(13)] * kernel_shared_local[(0)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(14)] * kernel_shared_local[(1)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(15)] * kernel_shared_local[(1)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(16)] * kernel_shared_local[(1)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(17)] * kernel_shared_local[(1)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(18)] * kernel_shared_local[(1)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(19)] * kernel_shared_local[(1)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(20)] * kernel_shared_local[(1)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(21)] * kernel_shared_local[(1)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(22)] * kernel_shared_local[(1)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(23)] * kernel_shared_local[(1)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(24)] * kernel_shared_local[(1)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(25)] * kernel_shared_local[(1)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(26)] * kernel_shared_local[(1)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(27)] * kernel_shared_local[(1)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(28)] * kernel_shared_local[(2)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(29)] * kernel_shared_local[(2)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(30)] * kernel_shared_local[(2)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(31)] * kernel_shared_local[(2)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(32)] * kernel_shared_local[(2)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(33)] * kernel_shared_local[(2)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(34)] * kernel_shared_local[(2)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(35)] * kernel_shared_local[(2)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(36)] * kernel_shared_local[(2)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(37)] * kernel_shared_local[(2)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(38)] * kernel_shared_local[(2)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(39)] * kernel_shared_local[(2)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(40)] * kernel_shared_local[(2)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(41)] * kernel_shared_local[(2)]));
        compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared_local[(42)] * kernel_shared_local[(3)]));
        compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared_local[(43)] * kernel_shared_local[(3)]));
        compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared_local[(44)] * kernel_shared_local[(3)]));
        compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared_local[(45)] * kernel_shared_local[(3)]));
        compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared_local[(46)] * kernel_shared_local[(3)]));
        compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared_local[(47)] * kernel_shared_local[(3)]));
        compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared_local[(48)] * kernel_shared_local[(3)]));
        compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared_local[(49)] * kernel_shared_local[(3)]));
        compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared_local[(50)] * kernel_shared_local[(3)]));
        compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared_local[(51)] * kernel_shared_local[(3)]));
        compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared_local[(52)] * kernel_shared_local[(3)]));
        compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared_local[(53)] * kernel_shared_local[(3)]));
        compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared_local[(54)] * kernel_shared_local[(3)]));
        compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared_local[(55)] * kernel_shared_local[(3)]));
      }
    }
  }
  compute[(((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)))] = compute_local[(0)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 1))] = compute_local[(1)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 2))] = compute_local[(2)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 3))] = compute_local[(3)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 4))] = compute_local[(4)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 5))] = compute_local[(5)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 6))] = compute_local[(6)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 28))] = compute_local[(7)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 29))] = compute_local[(8)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 30))] = compute_local[(9)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 31))] = compute_local[(10)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 32))] = compute_local[(11)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 33))] = compute_local[(12)];
  compute[((((((((int)blockIdx.z) * 18816) + (((int)threadIdx.z) * 784)) + (((int)blockIdx.y) * 56)) + (((int)threadIdx.x) * 7)) + 34))] = compute_local[(13)];
}

int main(int argc, char *argv[]){
    dim3 grid(1,14,4);
    dim3 block(4,1,24);
    int C = atoi(argv[1]);
    int H = atoi(argv[3]);
    int W = atoi(argv[4]);
    int N = atoi(argv[2]);
    int data_size = C*H*W;

    float *input;
    cudaMalloc(&input,data_size*sizeof(float));
    float *weight;
    cudaMalloc(&weight,N*C*9*sizeof(float));
    float *output;
    cudaMalloc(&output,N*H*W*sizeof(float));

    cudaDeviceSynchronize();
    float inference_time = 0.0f;
    cudaEvent_t event_start;
    cudaEvent_t event_stop;
    cudaEventCreate(&event_start);
    cudaEventCreate(&event_stop);
    for(int i=0;i<1024;++i){
        cudaEventRecord(event_start);
        default_function_kernel0<<<grid,block>>>(input,weight,output);
        cudaEventRecord(event_stop);
        cudaEventSynchronize(event_stop);
        float temp_time;
        cudaEventElapsedTime(&temp_time, event_start, event_stop);
        inference_time += temp_time;
    }
    cout<<C<<","<<N<<","<<H<<","<<W<<","<<inference_time/1024<<endl;
    return 0;
}
